x-to-kafka-service:
  search-words:
    - Java
    - Microservices
    - Event driven design
    - Spring boot
    - Kafka
    - ELK stack
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 20
  mock-sleep-ms: 1000

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2
  maxAttempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: x-topic
  topic-names-to-create:
    - x-topic
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.LongSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 50
  linger-ms: 1000
  request-timeout-ms: 60000
  retry-count: 5