server:
  port: 8184
  servlet:
    context-path: /elastic-query-web-client

elastic-query-web-client:
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    base-url: 'http://localhost:8183/elastic-query-service/documents'
  query-by-text:
    method: POST
    uri: "/get-document-by-text"

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: 'elastic-query-web-client'
            client-secret: 'slPqMSr3SYDDsokrxBSbSZA6cOrXaEQO'
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          keycloak:
            issuerUri: http://localhost:9091/auth/realms/microservices-realm

user-config:
  username: test
  password: test
  roles: USER